spring.application.name=kafka-exactly-once-cashback

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cashbackdb
spring.datasource.username=cashbackuser
spring.datasource.password=cashback123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Actuator — expose health and metrics endpoints
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
